apiVersion: v1
kind: Secret
metadata:
  name: painel-amanaje-secrets
  namespace: painel-amanaje
type: Opaque
stringData:
  POSTGRES_PASSWORD: "airflow"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres:5432/airflow"
  AIRFLOW__CORE__FERNET_KEY: "POUpJctdxFXdtaiPxrgt9c5bWPaiXd3XiEXDHsap_6E="
  _AIRFLOW_WWW_USER_PASSWORD: "airflow"
